[package]
name = "minimal-cargo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "check"
path = "src/check.rs"

[dependencies]
cargo = { git = "https://github.com/rust-lang/cargo.git" }
serde_json = "1.0.140"
